### ISSUE TITLE
Support sqlite aggregate functions in sqlc-gen-zombiezen

### ISSUE THREAD

**Issue by bannatech** [delaneyj/toolbelt#19]
When generating code, sql statements containing [aggregate functions](https://www.sqlite.org/lang_aggfunc.html) fail: 

    # package zz
    error generating code: process: error running command panic: toGoType unhandled type 'any' for column 'max'

    goroutine 1 [running]:
    github.com/delaneyj/toolbelt/sqlc-gen-zombiezen/zombiezen.toGoType(0xc00025e420)
            third_party/go/sqlc_gen_zombiezen/_sqlc_gen_zombiezen_src/sqlc-gen-zombiezen/zombiezen/queries.go:134 +0x28e
    github.com/delaneyj/toolbelt/sqlc-gen-zombiezen/zombiezen.generateQueries.func2(_, _)
            third_party/go/sqlc_gen_zombiezen/_sqlc_gen_zombiezen_src/sqlc-gen-zombiezen/zombiezen/queries.go:49 +0x78
    github.com/samber/lo.Map[...]({0xc000078668?, 0x1, 0x7}, 0xc0001a7c98?)
            pkg/linux_amd64/github.com/samber/lo/slice.go:30 +0xe2
    github.com/delaneyj/toolbelt/sqlc-gen-zombiezen/zombiezen.generateQueries(0xc0000e07e0)
            third_party/go/sqlc_gen_zombiezen/_sqlc_gen_zombiezen_src/sqlc-gen-zombiezen/zombiezen/queries.go:48 +0x345
    github.com/delaneyj/toolbelt/sqlc-gen-zombiezen/zombiezen.Generate({0xc00022c000?, 0x32d4?}, 0xc0000e07e0)
            third_party/go/sqlc_gen_zombiezen/_sqlc_gen_zombiezen_src/sqlc-gen-zombiezen/zombiezen/gen.go:25 +0x1a5
    main.run()
            third_party/go/sqlc_gen_zombiezen/_sqlc_gen_zombiezen_src/sqlc-gen-zombiezen/main.go:33 +0x11f
    main.main()
            third_party/go/sqlc_gen_zombiezen/_sqlc_gen_zombiezen_src/sqlc-gen-zombiezen/main.go:17 +0x13
            
Schema:

    CREATE TABLE IF NOT EXISTS test (
        id INTEGER PRIMARY KEY,
        data INTEGER NOT NULL
    );

Query:

    -- name: GetTest :one
    SELECT
        max(data)
    FROM
        test;

**Comment by delaneyj** [comment]
this is a sqlc issue unfortunately
